$kind: http-request
name: Get tasks
url: "{{BaseURL}}/{{task}}"
method: GET
scripts:
  - type: afterResponse
    code: "pm.test(\"Status code is 200\", function () {\r

      \    pm.response.to.have.status(200);\r

      });"
    language: text/javascript
order: 3458729201741284
